package: rex_address
version: '1.0.3'
author: Thomas Kaegi
supportpage: github.com/phoebusryan/rex_address

page:
    title: 'translate:title'
    perm: rex_address[]
    pjax: true
    icon: rex-icon fa-map-o
    subpages:
        config: { title: 'translate:config', perm: rex_address[config] }