package: rex_address
version: '1.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/rex_address

page:
    title: 'translate:title'
    perm: rex_address[]
    pjax: true
    icon: rex-icon fa-map-o
    subpages:
        address: { title: 'translate:address', perm: rex_address[address] }
        miscellaneous: { title: 'translate:miscellaneous', perm: rex_address[miscellaneous] }