package: address
version: '2.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/address

page:
    title: 'translate:title'
    perm: address[]
    pjax: true
    icon: rex-icon fa-map-o
    subpages:
        address: { title: 'translate:address', perm: address[address] }
        miscellaneous: { title: 'translate:miscellaneous', perm: address[miscellaneous] }